Repository crustio/crust-node, pull requests merged in 2020-07, with the labels that each got.

#41 Change spec 20200629
  etc/crust_chain_spec.json
Labels: maxwell

#42 Configurations generator
  .gitignore
  README.md
  config/config.json
  script/build_config.sh
  script/crust-client.sh
  script/utils.sh
Labels: enhancement

#44 Shell for install sgx driver
  .gitignore
  README.md
  scripts/install_sgx_driver.sh
Labels: enhancement, maxwell

#46 Change tee to sworker
  README.md
  config.yaml
  generator/config-gen/index.js
  generator/config-gen/karst-config.gen.js
  generator/config-gen/sworker-config.gen.js
  generator/schema/index.js
  generator/schema/sworker.schema.js
Labels: enhancement, maxwell

#47 Optimize generate configuration shell
  README.md
  scripts/gen_config.sh
Labels: enhancement, maxwell

#48 Downgrade docker compose
  generator/config-gen/index.js
Labels: maxwell

#49 Update chain docker image to 0.7.0
  generator/config-gen/chain-config.gen.js
Labels: maxwell

#50 Change chain spec to maxwell
  generator/config-gen/chain-config.gen.js
Labels: maxwell
